jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug workspace
        run: |
          pwd
          ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:v2 $GITHUB_WORKSPACE/backend
  

      - name: Push Backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:v2

      - name: Build Analyzer
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/analyzer:v2 $GITHUB_WORKSPACE/analyzer      

      - name: Push Analyzer
        run: docker push ${{ secrets.DOCKER_USERNAME }}/analyzer:v2
